### ISSUE TITLE
Writing error

### ISSUE THREAD

**Issue by adamgayoso** [theislab/anndata#286]
I upgraded to `scanpy==1.4.5`, which resulted in `anndata==0.7rc1 `.

Now, when I write an anndata object using

```
dataset_111.write("data/data.h5ad", compression="lzf")
```
I receive the errors below.

Downgrading to `0.6.22rc1` and `h5py==2.10.0` fixed the issue, though I'm not sure it's due to the h5py change.

```
AttributeError: 'numpy.int64' object has no attribute 'encode'

Above error raised while writing key 0 of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.
```

**Comment by falexwolf** [comment]
You can safely run Scanpy 1.4.5 with anndata `0.6.22.post1` and versions prior to it.

anndata 0.7 is still an rc and might have a couple of remaining bugs even after many weeks of testing in production.

We'll hopefully restore "lzf" compression soon.

**Comment by rosalindxu** [comment]
Hi! I tried to run the pbmc3k tutorial with Scanpy1.4.5, and encountered the same issue:

~/anaconda3/lib/python3.7/site-packages/h5py/_hl/base.py in _e(self, name, lcpl)
    136             try:
--> 137                 name = name.encode('ascii')
    138                 coding = h5t.CSET_ASCII

AttributeError: 'numpy.int64' object has no attribute 'encode'

**When I rolled anndata back to 0.6.22.post1, however, the method scanpy.read_10x_mtx no longer worked.** 

Could you let us know if anyone found a fix? Thanks!

**Comment by flying-sheep** [comment]
Please create a reproducible example that uses only publicly available data (optimally just some ndarrays and/or DataFrames created on the fly)

```py
AnnData(<insert_code_here>).write('test.h5ad')
```

**Comment by falexwolf** [comment]
I can't reproduce the error with `0.6.22.post1`. It runs through for me on macs and different Linux machines. The tutorial was indeed run with that version as is visible from the version string in the header of https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html.

The error with `0.7rc` is known and will be fixed soon.

Are you on the latest Scanpy?

**Comment by adamgayoso** [comment]
> You can safely run Scanpy 1.4.5 with anndata 0.6.22.post1 and versions prior to it.

Shouldn't the scanpy setup.py reflect this then?

**Comment by rosalindxu** [comment]
> I can't reproduce the error with `0.6.22.post1`. It runs through for me on macs and different Linux machines. The tutorial was indeed run with that version as is visible from the version string in the header of https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html.
> 
> The error with `0.7rc` is known and will be fixed soon.
> 
> Are you on the latest Scanpy?

Hi Alex,

Thanks for your prompt reply. I think I am on the latest Scanpy: here is the header when I run the pbmc3k tutorial: 

scanpy==1.4.5 anndata==0.6.22.post1 umap==0.3.10 numpy==1.17.2 scipy==1.3.1 pandas==0.25.1 scikit-learn==0.21.3 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1

Here is the end of the error message when I run anndata==0.6.22.post1: 

adata = sc.read_10x_mtx(
    './data/filtered_gene_bc_matrices/hg19/',  # the directory with the `.mtx` file
    var_names='gene_symbols',                  # use gene symbols for the variable names (variables-axis index)
    cache=True)                                # write a cache file for faster subsequent reading

~/anaconda3/lib/python3.7/site-packages/anndata/core/anndata.py in _args_from_dict(ddata)
   2155             if d_true_keys[true_key] is not None:
   2156                 for key in keys:
-> 2157                     if key in d_true_keys[true_key].dtype.names:
   2158                         d_true_keys[true_key] = pd.DataFrame.from_records(
   2159                             d_true_keys[true_key], index=key)

AttributeError: 'dict' object has no attribute 'dtype'

Do you think there is something wrong with my installation, etc.? Thanks!

**Comment by rosalindxu** [comment]
Hi -- - After discussing for about an hour, we found out the problem… **cache file**!

    - When I first used anndata==0.7rc1, which was automatically installed by scanpy==1.4.5, the read worked and it wrote a cache file when reading the pbmc3k dataset (in the tutorial) 
    -  However anndata==0.7rc1 could not write .h5ad in the scanpy.write functionality, so I switched to anndata==0.6.22.post1
    -  However, I did not delete the cache written by the newer anndata==0.7rc1
    - Then the older anndata tried to read the cache file written by the newer anndata, but couldn’t. So I got the reading error shown above
    - After deleting the cache folder, both read and write can work for anndata==0.6.22.post1

We see that the anndata version is already fixed to 0.6.22.post1 in scanpy==1.4.5.post1. Thank you!

-- Rosalind

**Comment by falexwolf** [comment]
I'm sorry about the confusion, here. It was my mistake to leave `0.7rc1` in the requirements for `1.4.5` - it was only meant to be temporary to get some CI stuff working - after a week of checking and testing I still didn't notice. Sorry again!

**Comment by flying-sheep** [comment]
Don’t worry about it, I doubt anyone lost work this way, and now we have a few useful bug reports.

More or less useful, I’m still not sure if we can find the issue without anyone here providing a reproducible example.

@adamgayoso @rosalindxu can you please help?

> Please create a reproducible example that uses only publicly available data (optimally just some ndarrays and/or DataFrames created on the fly)

> ```py
> AnnData(<insert_code_here>).write('test.h5ad')
> ```

**Comment by adamgayoso** [comment]
I can't seem to reproduce the issue on randomly generated data.

**Comment by rosalindxu** [comment]
Hi : The code I was running was the **scanpy pbmc3k tutorial**. With **scanpy==1.4.5 anndata==0.7rc1**, 
Run: 

```
!mkdir data
!wget http://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz -O data/pbmc3k_filtered_gene_bc_matrices.tar.gz
!cd data; tar -xzf pbmc3k_filtered_gene_bc_matrices.tar.gz

import numpy as np
import pandas as pd
import scanpy as sc

results_file = './write/pbmc3k.h5ad'  # the file that will store the analysis results

adata = sc.read_10x_mtx(
    './data/filtered_gene_bc_matrices/hg19/',  # the directory with the `.mtx` file
    var_names='gene_symbols',                  # use gene symbols for the variable names (variables-axis index)
    cache=True)        

adata.write(results_file)

```
It will produce the writing error.

**Comment by flying-sheep** [comment]
Great, thank you, that should help!

**Comment by flying-sheep** [comment]
OK, so this is happening because `read_10x_mtx` essentially does

```py
adata.obs_names = pd.Series(name=0, values=...)
```

That’s because it reads the `barcodes.tsv` file into a data frame and takes the first column, which ends up naming this column “0”. And hdf5 can’t handle integers as names.

Since we *do* handle Index names (e.g. it could be called `"barcodes"` just fine), I’ll strip numeric Index names when setting them.
