### ISSUE TITLE
str read in as bytes in h5py 3.0.0

### ISSUE THREAD

**Issue by zktuong** [theislab/anndata#442]
Hi,

I'm not sure if this is the right place to raise this issue; I've noticed some read/write discrepencies with the `.obs` and `.var` slots when `h5py==3.0.0` is used.
Strings and indices within the data frames are returned as byte string rather than character (Unicode) string. This seems to work fine with `h5py==2.10.0`.

Package versions:
scanpy==1.6.0 anndata==0.7.4 umap==0.4.6 numpy==1.19.2 scipy==1.5.2 pandas==1.1.4 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.8.3 leidenalg==0.8.2

**Comment by rbf22** [comment]
I can confirm this behavior, and yes it is very annoying.

**Comment by ivirshup** [comment]
I've looked into this, and am a bit closer to a fix.

Basically, `h5py>3` will now read any variable length strings in as `bytes` objects. You can instead read the objects as string by calling `dataset.asstr()[:]`. We can use some information stored in the dtype to know whether the strings were written as `bytes` or `str` objects, so we use that to tell if we want to call the `asstr` method. Strangely, this would all be done on the `h5py` side in previous versions, but that behaviour has been removed  ¯\_(ツ)_/¯.

I haven't figured out how we can read structured arrays (like the output of `rank_genes_groups`) back in with the correct dtype. I'm following up with this here: https://github.com/h5py/h5py/issues/1751.

**Comment by genecell** [comment]
I got the same annoying error and also solved it by downgrading h5py to 2.10.0.

This error is so annoying @.@, and I spent several hours before I found the solution here. Thanks!

**Comment by AjayNairLab** [comment]
I also got this frustrating error. The error is so frustrating because you do not land on this page while searching for this error for many days. 
scanpy h5ad file read byte error b'' 
Solved by updating anndata
pip install anndata==0.7.5

**Comment by codymowery** [comment]
Upgrading to anndata=0.7.5 alone didn't work, but that + downgrading to h5py=2.10.0 did. Thanks!

**Comment by haskankaya-crick** [comment]
I have just experienced this error using `h5py==3.3.0; anndata==0.7.4`.

Downgrading to `h5py==2.10.0` resolved the issue.

It seems like this bug for me affected the reading of the file rather than the writing. When I loaded an `.h5ad` which I had previously saved v3.3.0, it now worked fine.

**Comment by haskankaya** [comment]
I have just experienced this error using `h5py==3.3.0; anndata==0.7.4`.

Downgrading to `h5py==2.10.0` resolved the issue.

It seems like this bug for me affected the reading of the file rather than the writing. When I loaded an `.h5ad` which I had previously saved from v3.3.0, it now worked fine. (n.b. I am using this via [scanpy](https://github.com/theislab/scanpy))

**Comment by ywangaz** [comment]
Hi, I experienced the same issue in #1480. Tried downgrading h5py to 2.10.0 but the issue persists, and it's not compatible with the latest scanpy.
package versions:
  ```
anndata                   0.8.0
  h5py                      3.8.0
  scanpy                    1.9.3
  scmer                     0.1.1
```

my error message:
```
>>> adata = scanpy.read_h5ad("data/abseq/outputs/abseq.h5Seurat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rsrch4/home/bcb/ywang74/condaenv/scmer/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 254, in read_h5ad
    return AnnData(**d)
TypeError: __init__() got an unexpected keyword argument 'active.ident'
```
data:
`levels(abseq@active.ident)
 [1] "0"  "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14"`

Could you help me with the issue? Thank you!

**Comment by flying-sheep** [comment]
AnnData 0.8 is 2 versions behind, try a newer version.
